from flask import Flask, render_template, request, send_file, Response
from datetime import datetime
import qrcode
import io, base64
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        link = request.form.get("link")

        # ✅ Generate QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=10,
            border=4,
        )
        qr.add_data(link)
        qr.make(fit=True)

        img = qr.make_image(fill_color="black", back_color="white")

        # Save to memory (for displaying on page)
        img_io = io.BytesIO()
        img.save(img_io, "PNG")
        img_io.seek(0)
        qr_base64 = base64.b64encode(img_io.getvalue()).decode("utf-8")

        return render_template("index.html", qr_code=qr_base64, link=link)

    return render_template("index.html")

@app.route('/download_pdf')
def download_pdf():
    link = request.args.get("link")
    if not link:
        return "No link provided", 400

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 100, "Forever QR Generator")

    # Subtitle
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 130, "Your Permanent QR Code")

    # ✅ Generate QR image
    qr_img = qrcode.make(link)
    qr_buffer = BytesIO()
    qr_img.save(qr_buffer, format="PNG")
    qr_buffer.seek(0)

    # Center QR with larger size
    qr_size = 300   # increased from 220 → 300
    qr_x = (width - qr_size) / 2
    qr_y = (height - qr_size) / 2
    qr_reader = ImageReader(qr_buffer)
    c.drawImage(qr_reader, qr_x, qr_y, width=qr_size, height=qr_size)

    # Show link below QR
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, qr_y - 30, f"Link: {link}")

    # Footer (sticks at bottom)
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawCentredString(width / 2, 30, "Generated by Forever QR Generator")

    c.showPage()
    c.save()

    buffer.seek(0)
    return send_file(
        buffer,
        as_attachment=True,
        download_name="ForeverQR.pdf",
        mimetype="application/pdf"
    )

@app.route("/about")
def about():
    return render_template("about.html")

@app.route("/sitemap.xml", methods=["GET"])
def sitemap():
    pages = []

    # Get all routes in app
    for rule in app.url_map.iter_rules():
        # Include only GET routes that are not parameters
        if "GET" in rule.methods and len(rule.arguments) == 0:
            url = request.host_url.rstrip("/") + str(rule.rule)
            pages.append({
                "loc": url,
                "lastmod": datetime.date.today().isoformat()
            })

    # Generate XML
    sitemap_xml = """<?xml version="1.0" encoding="UTF-8"?>\n"""
    sitemap_xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'

    for page in pages:
        sitemap_xml += "  <url>\n"
        sitemap_xml += f"    <loc>{page['loc']}</loc>\n"
        sitemap_xml += f"    <lastmod>{page['lastmod']}</lastmod>\n"
        sitemap_xml += "  </url>\n"

    sitemap_xml += "</urlset>"

    response = Response(sitemap_xml, mimetype="application/xml")
    return response

if __name__ == "__main__":
    app.run(debug=True)
